/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author owner
 */
public class ui extends javax.swing.JFrame {

    /**
     * Creates new form ui
     */
    public ui() {

        initComponents();

        this.selectencryptionkeybutton.setEnabled(false);
        this.startencryptionbutton.setEnabled(false);

        this.providedecryptionkeybutton.setEnabled(false);
        this.startvideodecryptionbutton.setEnabled(false);

        this.selectencvidtohide.setEnabled(false);
        this.hidevideobutton.setEnabled(false);

        this.extractVideoButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        mothertab = new javax.swing.JTabbedPane();
        encryptiontab = new javax.swing.JPanel();
        selectvideobutton = new javax.swing.JButton();
        selectencryptionkeybutton = new javax.swing.JButton();
        startencryptionbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        encryptvideomessage = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        keygentab = new javax.swing.JPanel();
        keygenbutton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        keygenmessage = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        decryptionvidtab = new javax.swing.JPanel();
        selectdecryptedvideobuton = new javax.swing.JButton();
        providedecryptionkeybutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        startvideodecryptionbutton = new javax.swing.JButton();
        descryptmessage = new javax.swing.JTextArea();
        hidevideotab = new javax.swing.JPanel();
        selectpicture = new javax.swing.JButton();
        selectencvidtohide = new javax.swing.JButton();
        hidevideobutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hidemessage = new javax.swing.JTextArea();
        hidevideotab1 = new javax.swing.JPanel();
        selectStegnaPicutre = new javax.swing.JButton();
        extractVideoButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        extractMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        selectvideobutton.setText("SELECT A VIDEO");
        selectvideobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectvideobuttonActionPerformed(evt);
            }
        });

        selectencryptionkeybutton.setText("SELECT ENCRYPTION KEY");
        selectencryptionkeybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectencryptionkeybuttonActionPerformed(evt);
            }
        });

        startencryptionbutton.setBackground(new java.awt.Color(0, 0, 255));
        startencryptionbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        startencryptionbutton.setForeground(new java.awt.Color(255, 255, 255));
        startencryptionbutton.setText("START ENCRYPTION");
        startencryptionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startencryptionbuttonActionPerformed(evt);
            }
        });

        encryptvideomessage.setColumns(20);
        encryptvideomessage.setRows(5);
        jScrollPane1.setViewportView(encryptvideomessage);

        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("Messge ");

        javax.swing.GroupLayout encryptiontabLayout = new javax.swing.GroupLayout(encryptiontab);
        encryptiontab.setLayout(encryptiontabLayout);
        encryptiontabLayout.setHorizontalGroup(
            encryptiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encryptiontabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(encryptiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectencryptionkeybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectvideobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(encryptiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encryptiontabLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addGroup(encryptiontabLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addComponent(startencryptionbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        encryptiontabLayout.setVerticalGroup(
            encryptiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encryptiontabLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(encryptiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encryptiontabLayout.createSequentialGroup()
                        .addComponent(selectvideobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(selectencryptionkeybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(encryptiontabLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startencryptionbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        mothertab.addTab("ENCRYPT VIDEO", encryptiontab);

        keygenbutton.setBackground(new java.awt.Color(51, 0, 204));
        keygenbutton.setForeground(new java.awt.Color(255, 255, 255));
        keygenbutton.setText("GENERATE KEY PAIR");
        keygenbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keygenbuttonActionPerformed(evt);
            }
        });

        keygenmessage.setColumns(20);
        keygenmessage.setRows(5);
        jScrollPane3.setViewportView(keygenmessage);

        jLabel4.setText("Message");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("KEY GENERATION TAB");
        jLabel5.setToolTipText("");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout keygentabLayout = new javax.swing.GroupLayout(keygentab);
        keygentab.setLayout(keygentabLayout);
        keygentabLayout.setHorizontalGroup(
            keygentabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keygentabLayout.createSequentialGroup()
                .addGap(0, 126, Short.MAX_VALUE)
                .addGroup(keygentabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keygentabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(keygentabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keygentabLayout.createSequentialGroup()
                        .addComponent(keygenbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keygentabLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))))
        );
        keygentabLayout.setVerticalGroup(
            keygentabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keygentabLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(keygenbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        mothertab.addTab("KEY GENERATION", keygentab);

        selectdecryptedvideobuton.setText("SELECT ECNCRYPTED VIDEO");
        selectdecryptedvideobuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectdecryptedvideobutonActionPerformed(evt);
            }
        });

        providedecryptionkeybutton.setText("PROVIDE DECRYPTION KEY");
        providedecryptionkeybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providedecryptionkeybuttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("VIDEO DECRYPTION TAB");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        startvideodecryptionbutton.setBackground(new java.awt.Color(51, 0, 255));
        startvideodecryptionbutton.setForeground(new java.awt.Color(255, 255, 255));
        startvideodecryptionbutton.setText("START VIDEO DECRYPTION");
        startvideodecryptionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startvideodecryptionbuttonActionPerformed(evt);
            }
        });

        descryptmessage.setColumns(20);
        descryptmessage.setRows(5);

        javax.swing.GroupLayout decryptionvidtabLayout = new javax.swing.GroupLayout(decryptionvidtab);
        decryptionvidtab.setLayout(decryptionvidtabLayout);
        decryptionvidtabLayout.setHorizontalGroup(
            decryptionvidtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decryptionvidtabLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(decryptionvidtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectdecryptedvideobuton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(providedecryptionkeybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(decryptionvidtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(decryptionvidtabLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(decryptionvidtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startvideodecryptionbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(decryptionvidtabLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(119, Short.MAX_VALUE))
                    .addGroup(decryptionvidtabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descryptmessage)
                        .addContainerGap())))
        );
        decryptionvidtabLayout.setVerticalGroup(
            decryptionvidtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decryptionvidtabLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(decryptionvidtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(decryptionvidtabLayout.createSequentialGroup()
                        .addComponent(selectdecryptedvideobuton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(providedecryptionkeybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(descryptmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(startvideodecryptionbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        mothertab.addTab("DECRYPT VIDEO", decryptionvidtab);

        selectpicture.setText("SELECT PICTURE");
        selectpicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectpictureActionPerformed(evt);
            }
        });

        selectencvidtohide.setText("SELECT ENCRYPTED VIDEO");
        selectencvidtohide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectencvidtohideActionPerformed(evt);
            }
        });

        hidevideobutton.setBackground(new java.awt.Color(51, 0, 204));
        hidevideobutton.setForeground(new java.awt.Color(255, 255, 255));
        hidevideobutton.setText("HIDE VIDEO NOW");
        hidevideobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidevideobuttonActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Message");

        hidemessage.setColumns(20);
        hidemessage.setRows(5);
        jScrollPane2.setViewportView(hidemessage);

        javax.swing.GroupLayout hidevideotabLayout = new javax.swing.GroupLayout(hidevideotab);
        hidevideotab.setLayout(hidevideotabLayout);
        hidevideotabLayout.setHorizontalGroup(
            hidevideotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hidevideotabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hidevideotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectencvidtohide, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectpicture, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(hidevideotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hidevideotabLayout.createSequentialGroup()
                        .addGroup(hidevideotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(hidevideobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        hidevideotabLayout.setVerticalGroup(
            hidevideotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hidevideotabLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hidevideotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hidevideotabLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hidevideobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hidevideotabLayout.createSequentialGroup()
                        .addComponent(selectpicture, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectencvidtohide, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(301, Short.MAX_VALUE))
        );

        mothertab.addTab("HIDE VIDEO", hidevideotab);

        selectStegnaPicutre.setText("SELECT STEGA IMAGE");
        selectStegnaPicutre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectStegnaPicutreActionPerformed(evt);
            }
        });

        extractVideoButton.setBackground(new java.awt.Color(51, 0, 204));
        extractVideoButton.setForeground(new java.awt.Color(255, 255, 255));
        extractVideoButton.setText("EXTRACT VIDEO NOW");
        extractVideoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractVideoButtonActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Message");

        extractMessage.setColumns(20);
        extractMessage.setRows(5);
        jScrollPane4.setViewportView(extractMessage);

        javax.swing.GroupLayout hidevideotab1Layout = new javax.swing.GroupLayout(hidevideotab1);
        hidevideotab1.setLayout(hidevideotab1Layout);
        hidevideotab1Layout.setHorizontalGroup(
            hidevideotab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hidevideotab1Layout.createSequentialGroup()
                .addComponent(selectStegnaPicutre, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(hidevideotab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(extractVideoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(hidevideotab1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        hidevideotab1Layout.setVerticalGroup(
            hidevideotab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hidevideotab1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(extractVideoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addGroup(hidevideotab1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(selectStegnaPicutre, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mothertab.addTab("EXTRACT VIDEO", hidevideotab1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mothertab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mothertab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectpictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectpictureActionPerformed

        // TODO add your handling code here:i
        selectencryptionkeybutton.setEnabled(false);
        startencryptionbutton.setEnabled(false);

        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Stega image to hide video", new String[]{"png", "jpg", "PNG", "JPEG"}));
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int accepted = jFileChooser1.showOpenDialog(this);

        if (accepted == JFileChooser.APPROVE_OPTION) {

            RSA_STEGA_IMPL.imageFile = jFileChooser1.getSelectedFile();

            this.hidemessage.append("Cover image Selected is ::::\n" + RSA_STEGA_IMPL.imageFile);

            selectencvidtohide.setEnabled(true);

            hidevideobutton.setEnabled(false);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_selectpictureActionPerformed

    private void keygenbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keygenbuttonActionPerformed
        // TODO add your handling code here:
        try {
            RSAKeyManager.keyGenHelper();
            JOptionPane.showMessageDialog(this, "Public key and private were generated successfully. Saved in project(software) directory");
            this.keygenmessage.setText("The key pairs has been generated. You can use the key to encrypt (public) and decrypt (private) the extracted.");
            //call the key generation method here
//        this.
            //call the key generation method here
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_keygenbuttonActionPerformed

    private void selectvideobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectvideobuttonActionPerformed
        // TODO add your handling code here:i
        selectencryptionkeybutton.setEnabled(false);
        startencryptionbutton.setEnabled(false);

        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Video Files", "mp4"));
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Video Files", "mp4"));
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Video Files", "mp4"));

        int accepted = jFileChooser1.showOpenDialog(this);

        if (accepted == JFileChooser.APPROVE_OPTION) {

            RSAStegaCrypt.videoToEncrypt = jFileChooser1.getSelectedFile().getAbsolutePath();
            System.out.println(RSAStegaCrypt.videoToEncrypt);
            startencryptionbutton.setEnabled(false);
            selectencryptionkeybutton.setEnabled(true);

        }
    }//GEN-LAST:event_selectvideobuttonActionPerformed

    private void selectencryptionkeybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectencryptionkeybuttonActionPerformed

        // TODO add your handling code here:i
        selectencryptionkeybutton.setEnabled(false);
        startencryptionbutton.setEnabled(false);

        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Encryption Public Key File", "key"));
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int accepted = jFileChooser1.showOpenDialog(this);

        if (accepted == JFileChooser.APPROVE_OPTION) {

            RSAStegaCrypt.publicKeyDir = jFileChooser1.getSelectedFile().getAbsolutePath();
            System.out.println(RSAStegaCrypt.publicKeyDir);
            startencryptionbutton.setEnabled(true);
            selectencryptionkeybutton.setEnabled(true);

        }
    }//GEN-LAST:event_selectencryptionkeybuttonActionPerformed

    private void startencryptionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startencryptionbuttonActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:
        try {
            RSAStegaCrypt.doEncryptRSAWithAES(new File(RSAStegaCrypt.videoToEncrypt));
            encryptvideomessage.setText("\nVideo encryption was successful. The video is now ready to be hidden...");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.err.print(e.getMessage());
        } finally {
        }

    }//GEN-LAST:event_startencryptionbuttonActionPerformed

    private void selectdecryptedvideobutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectdecryptedvideobutonActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:i
        selectencryptionkeybutton.setEnabled(false);
        startencryptionbutton.setEnabled(false);

        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Encryption Video ", "videnc"));
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("MP4 video", "mp4"));
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int accepted = jFileChooser1.showOpenDialog(this);

        if (accepted == JFileChooser.APPROVE_OPTION) {

            RSAStegaCrypt.videoToDecrypt = jFileChooser1.getSelectedFile().getAbsolutePath();
            this.descryptmessage.append("Encrypted video selected ::::\n" + RSAStegaCrypt.videoToDecrypt);

            startvideodecryptionbutton.setEnabled(false);
            providedecryptionkeybutton.setEnabled(true);

        }


    }//GEN-LAST:event_selectdecryptedvideobutonActionPerformed

    private void startvideodecryptionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startvideodecryptionbuttonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            System.out.println(RSAStegaCrypt.videoToDecrypt);
            String extension = RSAStegaCrypt.videoToDecrypt.split("\\.")[1];
            RSAStegaCrypt.doDecryptRSAWithAES(new File(RSAStegaCrypt.videoToDecrypt), extension);
            this.descryptmessage.append("\n" + "Decryption of the encrypted video \n" + RSAStegaCrypt.videoToDecrypt + " was successfull...");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
//            System.err.print(e.getMessage());
            e.printStackTrace();

        } finally {
        }
    }//GEN-LAST:event_startvideodecryptionbuttonActionPerformed

    private void providedecryptionkeybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providedecryptionkeybuttonActionPerformed
        // TODO add your handling code here:i
//        selectencryptionkeybutton.setEnabled(false);
//        startencryptionbutton.setEnabled(false);

        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Decryption Private Key File", "key"));
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int accepted = jFileChooser1.showOpenDialog(this);

        if (accepted == JFileChooser.APPROVE_OPTION) {

            RSAStegaCrypt.privateKeyDir = jFileChooser1.getSelectedFile().getAbsolutePath();
            System.out.println(RSAStegaCrypt.privateKeyDir);
            this.descryptmessage.append("\nDecryption  key selected ::::\n" + RSAStegaCrypt.privateKeyDir);

            startvideodecryptionbutton.setEnabled(true);
//            providedecryptionkeybutton.setEnabled(true);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_providedecryptionkeybuttonActionPerformed

    private void hidevideobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidevideobuttonActionPerformed
        // TODO add your handling code here:
        try {
            System.out.println(RSA_STEGA_IMPL.imageFile);
            RSA_STEGA_IMPL imageProcessor = new RSA_STEGA_IMPL(RSA_STEGA_IMPL.imageFile, this.hidemessage);
            imageProcessor.getAllPixelsFromOriginalImage();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_hidevideobuttonActionPerformed

    private void selectencvidtohideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectencvidtohideActionPerformed

        // TODO add your handling code here:i
        selectencryptionkeybutton.setEnabled(false);
        startencryptionbutton.setEnabled(false);

        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Encrypted video to hide", "videnc"));

        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int accepted = jFileChooser1.showOpenDialog(this);

        if (accepted == JFileChooser.APPROVE_OPTION) {

            RSA_STEGA_IMPL.encryptedVideoInputFile = jFileChooser1.getSelectedFile().getAbsolutePath();
            this.hidemessage.append("\n\nEncrypted video Selected is ::::\n" + RSA_STEGA_IMPL.encryptedVideoInputFile);

            hidevideobutton.setEnabled(true);

        }        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_selectencvidtohideActionPerformed

    private void selectStegnaPicutreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectStegnaPicutreActionPerformed
        // TODO add your handling code here:
        selectStegnaPicutre.setEnabled(true);
        extractVideoButton.setEnabled(false);

        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Stega image to extract video from", new String[]{"png", "jpg", "PNG", "JPEG"}));

        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int accepted = jFileChooser1.showOpenDialog(this);

        if (accepted == JFileChooser.APPROVE_OPTION) {

            RSA_STEGA_IMPL.stegaImageFileInput = jFileChooser1.getSelectedFile().getAbsolutePath();
            this.extractMessage.append("Stega image Selected is ::::\n" + RSA_STEGA_IMPL.stegaImageFileInput);

            extractVideoButton.setEnabled(true);
    }//GEN-LAST:event_selectStegnaPicutreActionPerformed
    }
    private void extractVideoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractVideoButtonActionPerformed
        // TODO add your handling code here:

        try {

            RSA_STEGA_IMPL.extractVideos(null, extractMessage);

//            extractMessage.append("Video is succssfully extracted...");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());

        }

    }//GEN-LAST:event_extractVideoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ui().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel decryptionvidtab;
    private javax.swing.JTextArea descryptmessage;
    private javax.swing.JPanel encryptiontab;
    private javax.swing.JTextArea encryptvideomessage;
    private javax.swing.JTextArea extractMessage;
    private javax.swing.JButton extractVideoButton;
    private javax.swing.JTextArea hidemessage;
    private javax.swing.JButton hidevideobutton;
    private javax.swing.JPanel hidevideotab;
    private javax.swing.JPanel hidevideotab1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton keygenbutton;
    private javax.swing.JTextArea keygenmessage;
    private javax.swing.JPanel keygentab;
    private javax.swing.JTabbedPane mothertab;
    private javax.swing.JButton providedecryptionkeybutton;
    private javax.swing.JButton selectStegnaPicutre;
    private javax.swing.JButton selectdecryptedvideobuton;
    private javax.swing.JButton selectencryptionkeybutton;
    private javax.swing.JButton selectencvidtohide;
    private javax.swing.JButton selectpicture;
    private javax.swing.JButton selectvideobutton;
    private javax.swing.JButton startencryptionbutton;
    private javax.swing.JButton startvideodecryptionbutton;
    // End of variables declaration//GEN-END:variables
}
